### PR TITLE
V1.8.0 dev

### PR DESCRIPTION
**Pull request by jwildfire**

### CODE REVIEW

**Comment by jwildfire** [comment]
@brittsikora - Tagged "v1.8.0-RC1", which is ready for regression testing.

**Comment by brittsikora** [comment]
Renderer Testing

[x] Codebook
[ ] AE Explorer
[x] AE Timelines
[ ] Results over Time
[ ] Shift Plot
[ ] Histogram
[ ] Outlier Explorer
[ ] Query Overview

Only Codebook and AE Timelines passed - nothing else will render properly or completely, so I am going to fail this release candidate

**Comment by jwildfire** [comment]
@brittsikora Please provide some details and/or screenshots describing the problems with the other renderers, and let us know what commit you were using to test.
 (092fba6dc49ebf8b8b3206e074108efae37016d7 is preferred)

**Comment by brittsikora** [comment]
AE Explorer is rendering blank categories and filtering by prevalence removes some of the + icons (see screenshots below)



I've been using v1.8.0-RC1 to test and it is not rendering Histogram, Results over Time, or Shift Plot.
The Outlier Explorer is throwing this


And the Query Overview is throwing this

**Comment by jwildfire** [comment]
@brittsikora Can you confirm that you're getting the same output using 092fba6dc49ebf8b8b3206e074108efae37016d7 as the version for webcharts.

**Comment by brittsikora** [comment]
I can confirm - still broken

**Comment by jwildfire** [comment]
Make sure to select the correct data set for each renderer. queries.csv for query-overview. ADBDS.csv for the safety-explorerer renderers using lab data.

**Comment by brittsikora** [comment]
Just completed the visual test suite in Chrome and IE - notes below

Visual Tests
Scatter Plots: Axis Types
[x] Testing Axis Types - linear vs. linear
[x] Testing Axis Types - linear vs. log
[x] Testing Axis Types - linear vs. ordinal
[x] Testing Axis Types - log vs. log
[x] Testing Axis Types - log vs. date
[x] Testing Axis Types - log vs. ordinal
[x] Testing Axis Types - ordinal vs. ordinal
[x] Testing Axis Types - ordinal vs. date
[x] Testing Axis Types - date vs. date

Scatter Plots: text/circle
[x] X:linear, Y:linear, Mark Type:circle, Mark Per: Element
[x] X:linear, Y:linear, Mark Type:circle, Mark Per: Group
[x] X:linear, Y:linear, Mark Type:text, Mark Per: Element
[x] X:linear, Y:linear, Mark Type:text, Mark Per: Group

Sizing: Margins
[x] Margin:top = 100
[x] Margin:top = 200
[x] Margin:bottom = 100
[x] Margin:bottom = 200
[x] Margin:left = 100
[x] Margin:Left = 200
[x] Margin:right = 100
[x] Margin:right = 200
[x] Margin:different_values set 1
[x] Margin:different_values set 2

Sizing: Not resizable
[x] Height:500
[x] Height:750
[x] Width:500
[x] Width:750
[ ] Width:750, Max Width:500
[ ] Width:500, Max Width:750
[ ] Height:500, Aspect: 0.5
[ ] Height:500, Aspect: 2

Bar Charts: Data Summaries + Grouping – Don’t visually test
[ ] Vertical Stacked Bar chart: SummarizeY = mean
[ ] Vertical Stacked Bar chart:summarizeY = Median
[ ] Vertical Bar chart:summarizeY = Min
[ ] Vertical Bar chart:summarizeY = Max
[ ] Vertical Bar chart:summarizeY = count
[ ] Vertical Bar chart:summarizeY = sum
[ ] Vertical Bar chart:summarizeY = percent

Bar Charts: Data Summaries
[x] Vertical Bar chart:summarizeY = Mean
[x] Vertical Bar chart:summarizeY = Median
[x] Vertical Bar chart:summarizeY = Min
[x] Vertical Bar chart:summarizeY = Max
[x] Vertical Bar chart:summarizeY = count
[x] Vertical Bar chart:summarizeY = sum

Bar Charts: Stacked Bars
[x] Stacked Vertical Bar chart:linear Y-axis
[x] Stacked Vertical bar chart: Histogram with 10 bins (no y-variable specified) with linear Y-axis
[x] Stacked Vertical Bar chart: log Y-axis
[x] Stacked Vertical Bar chart: date Y-axis
[x] Stacked Vertical Bar chart: Ordinal Y-axis
[x] Stacked Horizontal Bar chart:linear x-axis
[x] Stacked Horizontal bar chart: Histogram with 10 bins (no x-variable specified) with linear x-axis
[x] Stacked Horizontal Bar chart: log X-axis
[x] Stacked Horizontal Bar chart: date X-axis
[x] Stacked Horizontal Bar chart: Ordinal X-axis

Bar Charts: Grouped Bars
[x] Grouped Vertical Bar chart:linear Y-axis
[ ] Grouped Vertical bar chart: Histogram with 10 bins (no y-variable specified) with linear Y-axis
[x] Grouped Vertical Bar chart: log Y-axis
[x] Grouped Vertical Bar chart: date Y-axis
[x] Grouped Vertical Bar chart: Ordinal Y-axis
[x] Grouped Horizontal Bar chart: linear x-axis
[ ] Grouped Horizontal bar chart: Histogram with 10 bins (no x-variable specified) with linear x-axis
[x] Grouped Horizontal Bar chart: log X-axis
[x] Grouped Horizontal Bar chart: date X-axis
[x] Grouped Horizontal Bar chart: Ordinal X-axis

Bar Charts: Horizontal Bars
[x] Horizontal Bar chart:linear x-axis
[x] Horizontal bar chart: Histogram with 10 bins (no x-variable specified) with linear x-axis
[x] Horizontal Bar chart: log X-axis
[x] Horizontal Bar chart: date X-axis
[x] Horizontal Bar chart: Ordinal X-axis

Bar Charts: Vertical Bars
[x] Vertical Bar chart:linear x-axis
[x] Vertical bar chart: Histogram with 10 bins (no x-variable specified) with linear x-axis
[x] Vertical Bar chart: log X-axis
[x] Vertical Bar chart: date X-axis
[x] Vertical Bar chart: Ordinal X-axis

**Comment by brittsikora** [comment]
Regression testing continued:

[x] Codebook
[x] AE Explorer
[x] AE Timelines
[x] Results over Time
[x] Shift Plot
[x] Histogram
[x] Outlier Explorer
[x] Query Overview

**Pull request merged**
