### PR TITLE
Tweak to clone the object

### PR DESCRIPTION
**Pull request by jwildfire**
@nbryant minor tweak for next release.

### CODE REVIEW

**Comment by nbryant** [comment]
Object.assign isn't supported in any version of IE (see [here] (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility)), so this will have to wait.

**Comment by qspencer** [comment]
Can we use the polyfill on the page you linked to Nathan?

**Comment by nbryant** [comment]
Sure, we could make it work with the polyfill, but I'm hesitant about the code:utility ratio. I'm actually thinking of stripping out `lengthenRaw` and `getValType`, since Webcharts doesn't actually use them anywhere internally. I'd probably rather take them out and leave those sorts of utility functions up to another library or custom implementations. And that would reduce some code bloat!

**Comment by nbryant** [comment]
closing this since there are no plans to make changes any time soon.

**Pull request closed without merging**
